import Link from "next/link";
import "./globals.css";

interface Props {
    children: React.ReactNode;
}
type Topics = {
    id: string;
    title: string;
};
export const metadata = {
    title: "WEB tutorial",
    description: "Generated by egoing",
};
export default async function RootLayout({ children }: Props) {
    const response = await fetch("http://localhost:9999/topics");
    const topics = await response.json();
    console.log(topics);

    return (
        <html>
            <body>
                <h1>
                    <Link href="/">WEB</Link>
                </h1>
                <ol>
                    {topics.map((topic: Topics) => {
                        return (
                            <li key={topic.id}>
                                <Link href={`/read/${topic.id}`}>
                                    {topic.title}
                                </Link>
                            </li>
                        );
                    })}
                </ol>

                {children}
                <ul>
                    <li>
                        <Link href="/create">create</Link>
                    </li>
                    <li>
                        <Link href="/update/id">update</Link>
                    </li>
                    <li>
                        <button>delete</button>
                    </li>
                </ul>
            </body>
        </html>
    );
}
