import Link from "next/link";
import "./globals.css";

interface Props {
    children: React.ReactNode;
}
export const metadata = {
    title: "WEB tutorial",
    description: "Generated by egoing",
};
export default function RootLayout({ children }: Props) {
    return (
        <html>
            <body>
                <h1>
                    <Link href="/">WEB</Link>
                </h1>
                <ol>
                    <li>
                        <Link href="/read/1">html</Link>
                    </li>
                    <li>
                        <Link href="/read/2">css</Link>
                    </li>
                </ol>
                {children}
                <ul>
                    <li>
                        <Link href="/create">create</Link>
                    </li>
                    <li>
                        <Link href="/update/id">update</Link>
                    </li>
                    <li>
                        <button>delete</button>
                    </li>
                </ul>
            </body>
        </html>
    );
}
